
# For more details on configuration options, visit https://nvuillam.github.io/mega-linter/


# General configuration

APPLY_FIXES: none
PARALLEL: true
FLAVOR_SUGGESTIONS: false
UPDATED_SOURCES_REPORTER: false
FILEIO_REPORTER: false
TEXT_REPORTER: true
CONFIG_REPORTER: false
CLEAR_REPORT_FOLDER: true
LOG_FILE: none
LOG_LEVEL: ERROR
VALIDATE_ALL_CODEBASE: true
SHOW_ELAPSED_TIME: true
# IGNORE_GITIGNORED_FILES: true
AZURE_COMMENT_REPORTER: true
PRINT_ALL_FILES: true
DISABLE_ERRORS: false

#ignore files
FILTER_REGEX_EXCLUDE: (node_modules/|.*/)

# Linters and Tools Configuration
ENABLE_LINTERS:
  - PYTHON_PYLINT
  - BASH_SHELLCHECK
  - JAVA_CHECKSTYLE
  - JAVASCRIPT_ES
  - TSX_ESLINT
  - SWIFT_SWIFTLINT
  - PYTHON_BLACK
  - JSX_ESLINT
  - JAVASCRIPT_PRETTIER
  - JAVASCRIPT_STANDARD
  - TYPESCRIPT_ES
  - TYPESCRIPT_PRETTIER
  - ENV_DOTENV_LINTER
  - HTML_HTMLHINT
  - JSON_PRETTIER
  - MARKDOWN_MARKDOWNLINT
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - API_SPECTRAL
  - CLOUDFORMATION_CFN_LINT
  - DOCKERFILE_HADOLINT
  - TERRAFORM_TFLINT
  - SPELL_CSPELL


#report generation
MARKDOWN_SUMMARY_REPORTER: true
JSON_REPORTER: true