name: Build and Deploy Admin Web App

on:
  push:
    branches:
      - qa-github

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run azure_envs.sh to Create .env
        run: |
          chmod +x scripts/azure_envs.sh
          echo "Running azure_envs.sh..."
          ./scripts/azure_envs.sh || { echo "ERROR: azure_envs.sh failed to execute!"; exit 1; }
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          REGION: ${{ secrets.REGION }}
        
      - name: Verify .env File
        run: |
          echo "Checking files in the current directory..."
          ls -la
          if [ -f .env ]; then
            echo ".env file created successfully."
            cat .env
          else
            echo "ERROR: .env file not found!"
            exit 1
          fi

      - name: Install Dependencies and Build
        run: |
          npm install --force
          export NODE_OPTIONS=--max-old-space-size=8192
          npm run build

      - name: Verify dist Directory
        run: |
          if [ -d dist ]; then
            echo "✅ Build successful, dist directory exists."
            ls -la dist
          else
            echo "❌ ERROR: dist directory not found!"
            exit 1
          fi

      - name: Deploy to AWS (S3 and CloudFront)
        run: |
          source .env
          aws s3 sync dist s3://$ADMIN_S3_BUCKET --acl public-read
          aws cloudfront create-invalidation --distribution-id $ADMIN_DISTRIBUTION_ID --paths "/*" 
          echo "✅ Deployment Completed!"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          REGION: ${{ secrets.REGION }}
